# 4. 例外処理

コンストラクタやメソッドの処理実行中に何らかの異常が発生した場合に、プログラムまたは Java VM 
が処理を一時中断して対策を講じる仕組みを「例外処理」と呼びます。

例外処理では、異常が発生した箇所で「例外オブジェクトのスロー」という形でプログラムを一時中断します。
中断したプログラムは「例外オブジェクトのキャッチ」によってリカバリ処理を行います。

例外処理は Java の言語仕様の中でも特に重要であり、また奥の深い仕組みでもあります。

## 4.1. 例外オブジェクト

例外オブジェクトは `Throwable` クラスを継承したインスタンスと規定されており、以下のように細分化されています。

* `Throwable` : すべての例外オブジェクトのスーパークラス。
サブクラスは `Error` および `Exception` だけであり、キャッチする意味を持たない。
  * `Error` : サブクラスを含め主に Java VM のエラーを表す。キャッチすべきではない。
  * `Exception` : サブクラスを含めプログラム内で発生したエラー一般を表す。キャッチしなければならない。
    * `RuntimeException` : サブクラスを含めプログラム内で発生したエラーのうちリカバリ不能なものを表す。
       Java SE においては基本的にバグが起因であり、キャッチする必要はない。
       Java EE においてはキャッチ任意の一般例外を意味する場合もある。

## 4.2. 例外のスロー

```
throw <例外オブジェクト>;
```

(例)
```
throw new IllegalArgumentException();  // 引数に不正な値が渡された
```

## 4.3. 例外処理

### 4.3.1. try-catch 節

try-catch 構文は基本的に以下の形式になります。

```
try {
    _例外がスローされる可能性がある処理_
} catch (例外) {
    _例外に対するリカバリ処理_
} finally {
    _try-catch 構文の最後に必ず実行される処理_
}
```

キャッチすべき例外が複数存在する場合は、以下の例のように catch (例外) { ... } が複数存在します。
また、finally { ... } の処理が必要ない場合は、finally 自体を省略することもできます。
finally はファイルやネットワークなど、終了処理を必ず行わなければならない処理のために用意されています。

### 4.3.2. throws 句

```
public int read(byte[] buf) throws IOException {
  ...
}
```
